### PR TITLE
Declare parameters in topic namespace

### PR DESCRIPTION
**Pull request by lukaszmitka**
Fix for https://github.com/ros-perception/image_transport_plugins/issues/57, declare parameters for each topic under topic namespace.

### CODE REVIEW

**Comment by brawner** [comment]
This works fine for me now, except when I went to confirm that the params were properly namespaced, I got the following error:

```
$ ros2 param list
Exception while calling service of node '/[image_transport_publisher_node]': None
```

I'm regularly working off of master, and things are changing fast right now, so I don't even know if it's 1). My system is borked 2). Unrelated bug in ros2 3). Something to do with this PR

I'm still investigating

**Comment by mjcarroll** [comment]
I'm not sure this this the correct workaround.  With the patch applied, I get parameters such as: 

```
/image_publisher:
  camera/image.format
  camera/image.jpeg_quality
  camera/image.png_level
  filename
  use_sim_time
/image_subscriber:
  mode
  transport
  use_sim_time
```

These parameters aren't configurable via the `--param` CLI option, I get an error such as:

```
'Couldn't parse parameter override rule: '--param camera/image.jpeg_quality:=1'. Error: Expected lexeme type 22, got 19 at index 6, at /home/michael/workspaces/ros2_foxy/src/ros2/rcl/rcl/src/rcl/lexer_lookahead.c:228, at /home/michael/workspaces/ros2_foxy/src/ros2/rcl/rcl/src/rcl/arguments.c:329'
```

**Comment by mjcarroll** [comment]
Part of this is probably due to me passing `camera/image` in as the topic for `image_transport`, but I think that isn't unreasonable to get the set of topics that you would expect, eg:

```
/camera/image
/camera/image/compressed
/camera/image/compressedDepth
/camera/image/theora
/parameter_events
/rosout
```

I believe that the correct approach would be to convert the topic `/` to `.` to match how parameters are namespaced.

**Comment by mjcarroll** [comment]
@lukaszmitka friendly ping

**Comment by yuraSomatic** [comment]
please, merge this finally.

**Comment by olivier-haddad** [comment]
This PR fixes this issue: [Failed to load plugin image_transport/compressed_pub #1530](https://github.com/IntelRealSense/realsense-ros/issues/1530)
ROS2 foxy users currently have to fork and apply this PR manually to get the package to work on foxy.
Please merge and release.

**Comment by berndpfrommer** [comment]
Can this please be merged and released? I'm getting the same error message for a new code base I'm developing, so this does not just affect the realsense driver.
Thanks!

**Comment by AmaurX** [comment]
Hello! This is a friendly ping to the amazing maintainers of Foxy! It would be great to merge and release this, as it can easily affect a lot of users! Cheers and thanks for all the hard work

**Review by AmaurX — APPROVED** [review]

**Comment by doisyg** [comment]
Would love to see this merged too. Is package still maintained ?

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
