### PR TITLE
add params for jpeg compression

### PR DESCRIPTION
**Pull request by furushchev**
This PR adds support of optional params on jpeg compression.

### CODE REVIEW

**Comment by furushchev** [comment]
Build on travis failed on `rosdep install` which is not related to the change introduced here:

```
Errors were encountered while processing:
 /var/cache/apt/archives/python-catkin-pkg-modules_0.4.12-1_all.deb
 /var/cache/apt/archives/python-catkin-pkg_0.4.12-100_all.deb
 /var/cache/apt/archives/python-catkin-tools_0.4.5-1_all.deb
 /var/cache/apt/archives/python-rospkg-modules_1.1.9-1_all.deb
 /var/cache/apt/archives/python-rosdistro-modules_0.7.4-1_all.deb
 /var/cache/apt/archives/python-rosdistro_0.7.4-100_all.deb
 /var/cache/apt/archives/python-rospkg_1.1.9-100_all.deb
 /var/cache/apt/archives/python-rosdep_0.15.1-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo apt-get install -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin" failed and exited with 100 during .
```

**Comment by furushchev** [comment]
@jkammerl @dirk-thomas (I'm not sure who is maintaining, sorry), could you restart the test?

**Comment by dirk-thomas** [comment]
You will need to update the Travis configuration to explicitly upgrade the `dpkg` package via `apt` before trying to install the `python-*` packages.

(PS: I won't be reviewing and/or merging this PR though since I am not the maintainer of theis repo / package.)

**Comment by furushchev** [comment]
@dirk-thomas Thank you for advice!
The tests of this repository is now enabled only on indigo/jade distro and I had to change almost the entire content of `.travis.yml`, so I made another PR to check if the existing code pass the tests.

I also updated this PR to use the commit of https://github.com/ros-perception/image_transport_plugins/pull/36.

**Comment by dgossow** [comment]
Merged #36.

Could you pull indigo-devel into your branch? The diff is either displayed wrong or the two branches have diverged.

**Comment by furushchev** [comment]
@dgossow Thank you for the review! Reset to indigo-devel and cherry picked the commit.

**Comment by dgossow** [comment]
lgtm

**Pull request merged**
