### PR TITLE
[ADD] flag for jpeg compression of bayer format

### PR DESCRIPTION
**Pull request by wodtko**
This PR adds a flag that allows for jpeg compression of Bayer encoded images.
Although I fully understand why one does not want a lossy compression of Bayer encoded image, it worked pretty well for us when testing it with multiple camera images.

We really want to use compressed Bayer images to get recordings smaller, e.g. we record 10Hz image_streams of 8 cameras with 3MP each.
With this PR there is no need for "inflating" the data to a color image prior to compression.

### CODE REVIEW

**Comment by wodtko** [comment]
is there any reason for not introducing this this parameter?
We are using this functionality every time, but we need to keep it forked...

**Comment by wodtko** [comment]
conflicts are fairly simple and I will solve them, if the general idea is welcomed.

**Comment by andrei-ng** [comment]
I would also be interested in this, any maintainer willing to review this? @wodtko , you may be interested in my comment on #68

**Comment by wodtko** [comment]
Thanks for bringing it up again @andrei-ng :D
I was only using ROS2 in this specific context, so I'm not sure about the exact issue in ros noetic.

However, different to the result in the issue mentioned, the bayer image is currently converted to a mono image prior to compression.
Thus, there is no way of retrieving a color image afterwards...
This PR adds a separate section for handling bayer formats to omit the mono color conversion.

**Comment by andrei-ng** [comment]
> Thanks for bringing it up again @andrei-ng :D I was only using ROS2 in this specific context, so I'm not sure about the exact issue in ros noetic.
> 
> However, different to the result in the issue mentioned, the bayer image is currently converted to a mono image prior to compression. Thus, there is no way of retrieving a color image afterwards... This PR adds a separate section for handling bayer formats to omit the mono color conversion.

@wodtko , thanks for the clarification. I haven't used ROS2 in this context. I hope that by the time I use it, your PR will be merged :) .

**Comment by wodtko** [comment]
Well, if anyone would review my changes, I would be happy to resolve any CI issues.
(mainly rebasing this PR)

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to fix the conflicts?

**Comment by wodtko** [comment]
All conflicts are fixed, and the number of lines changed was reduced.

I would highly appreciate any review/merge.

**Review by zkeyg — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
