### PR TITLE
Add legacy constants when using opencv4.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR adds compatibility for OpenCV4 (by including a legacy header if necessary).

### CODE REVIEW

**Comment by hgaiser** [comment]
I don't quite see why Travis fails, it seems unrelated to the changes made in this PR.

**Comment by v4hn** [comment]
Thank you for the patch, it's obviously backward compatible and works with OpenCV4. :+1:

**Comment by hgaiser** [comment]
Any update on this ? @dgossow ?

**Review by dgossow — APPROVED** [review]

**Comment by dgossow** [comment]
@wjwwood can you help here? The CI build seems to fail due to some misconfiguration.

```
The command "sudo apt-get install -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin" failed and exited with 100 during .
```

**Comment by dgossow** [comment]
@mjcarroll - are you maintaining this package perhaps? Or @vrabaud feels obligated to do so?

I was briefly compelled to take ownership of this by my boss but never really cared much about this.

**Comment by v4hn** [comment]
> I was briefly compelled to take ownership of this by my boss but never really cared much about this.

I believe many packages in ros-perception are not maintained anymore and some are  stuck for quite some time although rather trivial patches are available. You/your company would do a lot of people a huge favor if you would help to get some of them fixed and released! :+1: 
After all almost everyone expects stuff like the transport plugins to stay available.

**Comment by dgossow** [comment]
The story is really that this was during the last days of Willow Garage, when a lot of people were leaving and package ownership was redistributed, so a long time ago.

Unfortunately, I cannot fix the failing CI build as I don't have any access permissions or knowledge of how it was set up, but the build failure looks like a misconfiguration and not related to this PR.

Since there has been no reaction from the pinged OSRF folks, I'll cross my fingers and merge now.

**Comment by dgossow** [comment]
Thanks for the contribution!

**Comment by mjcarroll** [comment]
Hey @dgossow, I'm generally maintaining the ROS 2 forks, in conjunction with Intel on the perception stuff.  I think that the ROS1 maintenance is kind of in limbo pending any sort of response from @vrabaud.  Since these are important community packages, it may be time to take over ROS1 maintainership without appropriate go ahead.

**Comment by dgossow** [comment]
Not sure what you're implying here. Do you want to take over maintenance of this? Great!

I'm happy to not maintain this anymore, since I never really did maintain this in the first place. In fact I was surprised to see my name in the package.xml. I just felt sorry about all the unanswered PRs.

**Comment by mjcarroll** [comment]
@dgossow Ah, just put the pieces together, that's why your name seemed familiar.  No implications, I just didn't realize that you were currently maintaining.  I actually thought that Vincent had almost all of the ros-perception packages, so I'm sort of surprised to see your name on there as well ;)

Since I'm doing the ROS2 branches, I'm happy to at least get ROS PRs merged when they come up, if you are not interested in maintaining anymore.

When I was referring to "ROS1 maintenance is kind of in limbo", it was specifically in reference to some of the ros-perception packages that Vincent has historically maintained.  I think a few people have pinged him to try to step up as maintainers on those packages, but haven't made any progress on that front.

**Comment by dgossow** [comment]
Yes, I am not really interested in maintaining this. I never really maintained it. I am sorry if this was expected of me since I clearly do not meet those expectations. I am also not particularly knowledgeable of this codebase so I'm not especially qualified either.

**Pull request merged**
